# Generated by Django 6.1.2 on 2026-10-08 03:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('crs', models.CharField(blank=True, max_length=64)),
                ('feature_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('layer', models.CharField(blank=True, max_length=255)),
                ('geometry_type', models.CharField(max_length=32)),
                ('geometry', models.JSONField(null=True)),
                ('crs', models.CharField(max_length=64)),
                ('properties', models.JSONField(default=dict)),
                ('area_m2', models.FloatField(null=True)),
                ('length_m', models.FloatField(null=True)),
                ('projected_crs', models.CharField(blank=True, max_length=64)),
                ('measurement_status', models.CharField(choices=[('OK', 'Ok'), ('NOT_REQUIRED', 'Not Required'), ('UNSUPPORTED', 'Unsupported'), ('EMPTY', 'Empty'), ('ERROR', 'Error')], max_length=20)),
                ('measurement_note', models.CharField(blank=True, max_length=255)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='files.uploadedfile')),
            ],
            options={
                'ordering': ['index'],
                'constraints': [models.UniqueConstraint(fields=('file', 'index'), name='unique_feature_index_per_file')],
            },
        ),
    ]
